image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./gradlew build
    command: ./gradlew run
    name: backend

  - init: cd vue && npm install && gp sync-done npmInstalled
    command: npm run serve
    name: Frontend

  - command: gp sync-await npmInstalled && cd vue && vue ui
    name: Vue UI

ports:
  - port: 8080
    onOpen: ignore
  - port: 8081
    onOpen: open-browser

vscode:
  extensions:
    - mathiasfrohlich.Kotlin@1.7.1:zRxka5i+6/G9r7KC3xmyXQ==
    - octref.vetur@0.26.0:XwSAQhAxIqA9o5EWFvF6Ag==