image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./gradlew build
#name: Gradle Build
    command: ./gradlew run
    name: Application Server
  - init: cd vue && npm install
    command: cd vue && vue ui
    name: Frontend

ports:
  - port: 8080
#onOpen: open-preview # do not open preview, because there is nothing served on /
  - port: 8081

vscode:
  extensions:
    - mathiasfrohlich.Kotlin@1.7.1:zRxka5i+6/G9r7KC3xmyXQ==
    - octref.vetur@0.26.0:XwSAQhAxIqA9o5EWFvF6Ag==